package com.dfm.thin.model;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * ProductType definition.
 * 
 * This file was generated by Ignite Web Console (04/26/2019, 01:38)
 **/
public class ProductType implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for createdAt. */
    private Timestamp createdAt;

    /** Value for updatedAt. */
    private Timestamp updatedAt;

    /** Value for description. */
    private String description;

    /** Value for name. */
    private String name;

    /** Empty constructor. **/
    public ProductType() {
        // No-op.
    }

    /** Full constructor. **/
    public ProductType(Timestamp createdAt,
                       Timestamp updatedAt,
                       String description,
                       String name) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.description = description;
        this.name = name;
    }

    /**
     * Gets createdAt
     * 
     * @return Value for createdAt.
     **/
    public Timestamp getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets createdAt
     * 
     * @param createdAt New value for createdAt.
     **/
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets updatedAt
     * 
     * @return Value for updatedAt.
     **/
    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets updatedAt
     * 
     * @param updatedAt New value for updatedAt.
     **/
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof ProductType))
            return false;
        
        ProductType that = (ProductType)o;

        if (createdAt != null ? !createdAt.equals(that.createdAt) : that.createdAt != null)
            return false;
        

        if (updatedAt != null ? !updatedAt.equals(that.updatedAt) : that.updatedAt != null)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = createdAt != null ? createdAt.hashCode() : 0;

        res = 31 * res + (updatedAt != null ? updatedAt.hashCode() : 0);

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (name != null ? name.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "ProductType [" + 
            "createdAt=" + createdAt + ", " + 
            "updatedAt=" + updatedAt + ", " + 
            "description=" + description + ", " + 
            "name=" + name +
        "]";
    }
}