package com.dfm.thin.model;

import java.io.Serializable;

/**
 * Product definition.
 * 
 * This file was generated by Ignite Web Console (04/27/2019, 18:13)
 **/
public class Product implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for description. */
    private String description;

    /** Value for name. */
    private String name;

    /** Value for url. */
    private String url;

    /** Value for typeId. */
    private long typeId;

    /** Value for id. */
    private long id;

    /** Empty constructor. **/
    public Product() {
        // No-op.
    }

    /** Full constructor. **/
    public Product(String description,
        String name,
        String url,
        long typeId,
        long id) {
        this.description = description;
        this.name = name;
        this.url = url;
        this.typeId = typeId;
        this.id = id;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets url
     * 
     * @return Value for url.
     **/
    public String getUrl() {
        return url;
    }

    /**
     * Sets url
     * 
     * @param url New value for url.
     **/
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Gets typeId
     * 
     * @return Value for typeId.
     **/
    public long getTypeId() {
        return typeId;
    }

    /**
     * Sets typeId
     * 
     * @param typeId New value for typeId.
     **/
    public void setTypeId(long typeId) {
        this.typeId = typeId;
    }

    /**
     * Gets id
     * 
     * @return Value for id.
     **/
    public long getId() {
        return id;
    }

    /**
     * Sets id
     * 
     * @param id New value for id.
     **/
    public void setId(long id) {
        this.id = id;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Product))
            return false;
        
        Product that = (Product)o;

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (url != null ? !url.equals(that.url) : that.url != null)
            return false;
        

        if (typeId != that.typeId)
            return false;
        

        if (id != that.id)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = description != null ? description.hashCode() : 0;

        res = 31 * res + (name != null ? name.hashCode() : 0);

        res = 31 * res + (url != null ? url.hashCode() : 0);

        res = 31 * res + (int)(typeId ^ (typeId >>> 32));

        res = 31 * res + (int)(id ^ (id >>> 32));

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Product [" + 
            "description=" + description + ", " + 
            "name=" + name + ", " + 
            "url=" + url + ", " + 
            "typeId=" + typeId + ", " + 
            "id=" + id +
        "]";
    }
}