package com.dfm.thin.model;

import java.io.Serializable;

/**
 * Property definition.
 * 
 * This file was generated by Ignite Web Console (04/27/2019, 18:13)
 **/
public class Property implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for name. */
    private String name;

    /** Value for type. */
    private String type;

    /** Value for propertyId. */
    private long propertyId;

    /** Value for id. */
    private long id;

    /** Empty constructor. **/
    public Property() {
        // No-op.
    }

    /** Full constructor. **/
    public Property(String name,
        String type,
        long propertyId,
        long id) {
        this.name = name;
        this.type = type;
        this.propertyId = propertyId;
        this.id = id;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets type
     * 
     * @return Value for type.
     **/
    public String getType() {
        return type;
    }

    /**
     * Sets type
     * 
     * @param type New value for type.
     **/
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets propertyId
     * 
     * @return Value for propertyId.
     **/
    public long getPropertyId() {
        return propertyId;
    }

    /**
     * Sets propertyId
     * 
     * @param propertyId New value for propertyId.
     **/
    public void setPropertyId(long propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * Gets id
     * 
     * @return Value for id.
     **/
    public long getId() {
        return id;
    }

    /**
     * Sets id
     * 
     * @param id New value for id.
     **/
    public void setId(long id) {
        this.id = id;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Property))
            return false;
        
        Property that = (Property)o;

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (type != null ? !type.equals(that.type) : that.type != null)
            return false;
        

        if (propertyId != that.propertyId)
            return false;
        

        if (id != that.id)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = name != null ? name.hashCode() : 0;

        res = 31 * res + (type != null ? type.hashCode() : 0);

        res = 31 * res + (int)(propertyId ^ (propertyId >>> 32));

        res = 31 * res + (int)(id ^ (id >>> 32));

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Property [" + 
            "name=" + name + ", " + 
            "type=" + type + ", " + 
            "propertyId=" + propertyId + ", " + 
            "id=" + id +
        "]";
    }
}