package com.dfm.thin.model;

import java.io.Serializable;

/**
 * PropertyValue definition.
 * 
 * This file was generated by Ignite Web Console (04/27/2019, 18:13)
 **/
public class PropertyValue implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for value. */
    private String value;

    /** Value for propertyId. */
    private long propertyId;

    /** Value for id. */
    private long id;

    /** Empty constructor. **/
    public PropertyValue() {
        // No-op.
    }

    /** Full constructor. **/
    public PropertyValue(String value,
        long propertyId,
        long id) {
        this.value = value;
        this.propertyId = propertyId;
        this.id = id;
    }

    /**
     * Gets value
     * 
     * @return Value for value.
     **/
    public String getValue() {
        return value;
    }

    /**
     * Sets value
     * 
     * @param value New value for value.
     **/
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets propertyId
     * 
     * @return Value for propertyId.
     **/
    public long getPropertyId() {
        return propertyId;
    }

    /**
     * Sets propertyId
     * 
     * @param propertyId New value for propertyId.
     **/
    public void setPropertyId(long propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * Gets id
     * 
     * @return Value for id.
     **/
    public long getId() {
        return id;
    }

    /**
     * Sets id
     * 
     * @param id New value for id.
     **/
    public void setId(long id) {
        this.id = id;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof PropertyValue))
            return false;
        
        PropertyValue that = (PropertyValue)o;

        if (value != null ? !value.equals(that.value) : that.value != null)
            return false;
        

        if (propertyId != that.propertyId)
            return false;
        

        if (id != that.id)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = value != null ? value.hashCode() : 0;

        res = 31 * res + (int)(propertyId ^ (propertyId >>> 32));

        res = 31 * res + (int)(id ^ (id >>> 32));

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "PropertyValue [" + 
            "value=" + value + ", " + 
            "propertyId=" + propertyId + ", " + 
            "id=" + id +
        "]";
    }
}